### ISSUE TITLE
No sign in UI presented with brew cask install on Big Sur 11.2

### ISSUE THREAD

**Issue by drmarkpowell** [RobotsAndPencils/XcodesApp#106]
**Describe the bug**
No sign in UI is presented

**To Reproduce**
Click to install an XCode, no sign in UI is presented, error alert is immediately displayed.

**Expected behavior**
Some UI affordance to sign into Apple Developer Portal should appear

**Screenshots**
<img width="999" alt="Screen Shot 2021-02-09 at 10 15 59 AM" src="https://user-images.githubusercontent.com/1024831/107408459-dc2a7580-6abf-11eb-928d-97088b58d8e8.png">

**Version**
 - OS: Big Sur 11.2
 - Xcodes: brew cask install

**Comment by MattKiazyk** [comment]
Hi @drmarkpowell 

Thanks for the ticket. I'm going to close this in favour of tracking it in #22  

It's a known issue and it's not dependent on which way you install it from.

Thanks for letting is know and trying Xcodes!
