### ISSUE TITLE
Create alias for current active version at /Applications/Xcode.app

### ISSUE THREAD

**Issue by Kamik423** [RobotsAndPencils/XcodesApp#110]
I would love an option to always have the file in `/Applications/Xcodes.app` or the latest release version there and the latest beta in `/Applications/Xcodes Beta.app` or something similar. This would lead to the file not being removed from Dock.

Of course both these would have to be checked for existence first.

**Comment by interstateone** [comment]
Hey @Kamik423, that's a neat idea. I don't think Xcodes should install a version directly at those paths, but it could create an alias at those paths pointing at the current active (a.k.a. selected) version.

This is something that xcode-install does, and which we've considered for [`xcodes`](https://github.com/RobotsAndPencils/xcodes) as well.

A quick test of manually creating and changing an alias to point at different versions seems to do what I'd expect when the alias has been added to the Dock, so this might also solve the specific use case that you have.

**Comment by Kamik423** [comment]
I like the alias idea.

**Comment by MattKiazyk** [comment]
Closing this issue as Symbolic link automatic generation is implemented as an option in the above PR!

**Comment by juanjonol** [comment]
I'm afraid the OP request isn't really solved: symlinks are really useful for tools that are looking for `/Applications/Xcode.app`, but symlinks cannot be placed on the Dock, only macOS (Finder) alias can.

I don't think this is something that can be easily solved by Xcodes.app or `xcodes`, so I think this should remain closed.
