### ISSUE TITLE
Line break before download time estimator

### ISSUE THREAD

**Issue by Kamik423** [RobotsAndPencils/XcodesApp#113]
I love the new download time estimations progress bar—however I'd suggest adding a line break before the estimate so it is not

```
About 21

minutes, 25 seconds remaining
```

and instead have them all on the second row, maybe even shorten to something like

```
About 1:21:25 remaining
```

or

```
About 1 hour 21 minutes remaining
```

when it gets over an hour so it is shorter does not break line length.

<img width="900" alt="Screen Shot 2021-03-06 at 20 36 39" src="https://user-images.githubusercontent.com/16278233/110218830-13702480-7ebc-11eb-864a-3e49c441f0a6.png">

**Comment by MattKiazyk** [comment]
@Kamik423 - if you upgrade to the latest 1.0.5 - this should now be fixed. 

Thanks for the suggestion.
