### ISSUE TITLE
Installing an Xcode version with an M1 may fail

### ISSUE THREAD

**Issue by MattKiazyk** [RobotsAndPencils/XcodesApp#117]
**Describe the bug**
installing an Xcode on an M1 Mac when that Mac has not yet installed Rosetta will fail, I think because aria2 isn’t a universal binary and so it requires Rosetta, but the prompt to install Rosetta isn’t shown in this case. Not sure if that’s expected or not.

“The operation couldn’t be completed. Bad CPU type in executable.”

Anybody have an M1 to test?

**Comment by senmu** [comment]
It does indeed, fail
<img width="900" alt="Screen Shot 2021-04-14 at 3 15 29 PM" src="https://user-images.githubusercontent.com/818102/114780342-7f07a600-9d34-11eb-8b6e-11738bf20861.png">

**Comment by MattKiazyk** [comment]
Closed via #121

Added #122 so that we can track creating of a universal binary
