### ISSUE TITLE
'Make active' button has no effect

### ISSUE THREAD

**Issue by paulthorsteinson** [RobotsAndPencils/XcodesApp#125]
**Describe the bug**
With Xcode 12.4 as my current default, tapping 'make active' on 12.5 does nothing.

**To Reproduce**
set your default to 12.4 (or likely other) and then tap 'make active' on 12.5

**Expected behavior**
I expected it would make 12.5 the default

**Screenshots**
attached

**Version**
 - OS: 11.2.3
 - Xcodes: 1.0.5 (6)

<img width="968" alt="Screen Shot 2021-04-27 at 11 34 03 AM" src="https://user-images.githubusercontent.com/331285/116286645-b02ca100-a74c-11eb-845b-38717b8a6131.png">

**Comment by paulthorsteinson** [comment]
Further to this the open button also doesnt seem to do anything

**Comment by MattKiazyk** [comment]
Hey Paul - I've seen this before, but can't remember what the context was when it started happening.

Couple of things to try:
- restarting Xcodes? Restart the app?
- Reset your privileged helper - look at the script in https://github.com/RobotsAndPencils/XcodesApp/blob/main/Scripts/uninstall_privileged_helper.sh then reinstall via the Settings. 

Let me know if any of those don't work.

**Comment by paulthorsteinson** [comment]
@MattKiazyk unfortunately those did not work.  Most recent attempt on Big Sur 11.3

**Comment by MattKiazyk** [comment]
Curious if you have time @paulthorsteinson, if you download the source code, does it still happen in debug. If it does, that would easily tell where it is returning early, where we aren't handling an error

**Comment by paulthorsteinson** [comment]
So when I run the project and tap that button I get the 'install helper' dialog (whereas with the release version its installed already).  when I tap install it does nothing.  Then I go to preferences to install it there and get:
<img width="279" alt="Screen Shot 2021-04-28 at 3 23 56 PM" src="https://user-images.githubusercontent.com/331285/116474594-f0b41980-a835-11eb-8dc0-ea8ca2d0ce07.png">

**Comment by paulthorsteinson** [comment]
Note that I didn't have that same issue with the release build, just debug

**Comment by MattKiazyk** [comment]
Is there anything in the debug console when you run it?

Curious where in `HelperClient.install` it is failing? 

Is this an M1 Mac?

**Comment by aerickson14** [comment]
I just ran into this same situation. 

In my case, if I have Xcode open and do an action like `Make active`, it will work. If you close Xcode and press the button you will be prompted to install the privilege helper, but allowing that install will result in the "The operation couldn't be completed" alert @paulthorsteinson is getting above.

**Comment by aerickson14** [comment]
So after a bit more digging I found that in my case this error was occurring because I had opened up a version of the app that is run for unit tests.

Currently I have Xcodes.app located in 3 spots:
Release Install: `/Applications/Xcodes.app` (works as expected)
Debug Install when running from Xcode: `/Library/Developer/Xcode/DerivedData/Xcodes-.../Build/Products/Debug/Xcodes.app` (works as expected)
A version of the app created for running unit tests against: `/Library/Developer/Xcode/DerivedData/Xcodes-.../Build/Products/Test/Xcodes.app` (this is the one that that can reproduce the error described above)

**Comment by paulthorsteinson** [comment]
> Is there anything in the debug console when you run it?
> 
> Curious where in `HelperClient.install` it is failing?
> 
> Is this an M1 Mac?

Nothing showed up in the debug console
It wasn't obvious to me where it was failing because running it in debug mode was behaving differently in that it was prompting me to install the privileged helper each time.
Not an M1 Mac

**Comment by malonehedges** [comment]
encountering this bug still. wasn't having issues until recently

**Comment by ehmjaysee** [comment]
Getting same behavior with Xcode 13.0 on Intel Mac running Big Sur 11.6

I installed Xcode 13.0.0-Release.Candidate.app using Xcodes 1.1.0 and now I can see version 13.0 in the list with the checkmark indicating it was installed, however none of the button work: Make Activate, Open, or the arrow that opens the app folder. Note I can open Xcode13 from Finder no problem.

**Comment by MattKiazyk** [comment]
Hi @malonehedges @ehmjaysee 

See a possible solution here: https://github.com/RobotsAndPencils/XcodesApp/issues/154

Let me know if that solves it?

**Comment by ehmjaysee** [comment]
Worked!

**Comment by paulthorsteinson** [comment]
Thanks @MattKiazyk
