### ISSUE TITLE
Actions that first require login should continue after a successful login

### ISSUE THREAD

**Issue by aerickson14** [RobotsAndPencils/XcodesApp#132]
**Describe the bug**
If a user is attempting to perform an action that requires a login session (refreshing list of available Xcodes, installing a new Xcode) they will be presented with a login sheet. After successfully logging in though the action that was previously being performed does not resume.

**To Reproduce**
- Start with a logged out session
- Tap install on any Xcode that is not currently installed
- You should be prompted to sign in
- Provide valid sign in credentials

**Expected behavior**
The install process starts

**Actual behaviour**
The install process is cancelled/interrupted by the login flow

**Version**
 - OS: 11.2.3
 - Xcodes: 1.0.5 (6)

**Comment by Paddy613** [comment]
[]()

**Comment by Paddy613** [comment]
@aerickson14

**Comment by Paddy613** [comment]
Bug

**Comment by MattKiazyk** [comment]
As of v1.8 we no longer require apple accounts to download Xcode so these issues won't show up anymore 🥳
