### ISSUE TITLE
Ability to launch currently-active Xcode via scripting

### ISSUE THREAD

**Issue by fancyham** [RobotsAndPencils/XcodesApp#143]
**Tell us how we can improve Xcodes**

**Is your feature request related to a problem? Please describe.**

I love binding a key command to launch Xcode — it makes it super fast to get back into Xcode.  (I use Many Tricks' Butler app) 

However, the key binding I use launches an app called "Xcode.app"… which would work normally, but since Xcodes installs and activates different versions of the app, my macro/key binding now needs to launch "Xcode-13.0.0-Beta.3.app" (and tomorrow, Beta.4).

**What would you like to see? How would you like it to work?**

Feature request: 

Create a way to launch/switch the currently-activiated Xcode via scripting in Xcodes.  Perhaps via AppleScript?  Or perhaps by creating an alias that I can open (that changes when different Xcode is activated).

**Comment by parrots** [comment]
I was running into something similar with a script that assumed /Applications/Xcode.app as the root to some dev libraries.

Alternate proposal: symlink to make Xcode.app always point to whichever we say is the active one, via Xcodes. Obviously if we go Xcode-selecting on our own you can't control that, but if we use Xcodes it'd be nice.

(Or, if for some reason symlinks break anything else or break things like Alfred from actually seeing them, maybe just have an option that when we make an Xcode the active one it gets renamed to Xcode.app and the previously active one gets renamed back to a versioned name.)

**Comment by MattKiazyk** [comment]
Adding the ability to automatically create symbolic links (if it can) named `Xcode.app` when you Select/Activate through Xcodes in #200
