### ISSUE TITLE
Enhancement: Add custom install directory

### ISSUE THREAD

**Issue by MichaelJBerk** [RobotsAndPencils/XcodesApp#148]
**Tell us how we can improve Xcodes**
Customize what directory Xcode will install to.

As an example use case, I have an APFS volume for files that I share between my main Big Sur install and Monterey. I store the current Xcode beta in that volume so it can be accessed from either OS. Currently, this means I have to manually copy the new beta to the shared volume, then delete it from /Applications. I would like to be able to choose which directory the app will be installed to.

**Is your feature request related to a problem? Please describe.**
No

**What would you like to see? How would you like it to work?**
Beneath the "install" button in the sidebar, there could be a "Custom Directory" checkbox, with a button next to it to pick which directory to install it to

**Comment by h3x4d3c1m4l** [comment]
Another use case for this functionality would be for Macs with small disks. Xcode itself takes a lot of space, then updating it using the App Store requires (temporarily) another large amount of disk space. Its iOS simulator needs a lot of space too...

Being able to manage Xcode instances on another disk would be very helpful with keeping Xcode internal disk usage to a minimum.
