### ISSUE TITLE
The Verifying "Xcode-x.x.x" window never goes away after installation

### ISSUE THREAD

**Issue by BrentMifsud** [RobotsAndPencils/XcodesApp#149]
**Describe the bug**
Not sure if the app has any control over this, could be bug in macOS Big Sur.

When installing Xcode, after the download and installation is complete, the filesystem window never seems to go away.

**To Reproduce**
This is how I have been able to reproduce it every time:
1. install a version of xcode
2. when you see the "Verifying Xcode" window (see screenshot), minimize it to the dock.
3. when its finished it will never go away.

**Expected behavior**
The loading bar window should disappear after its finished unarchiving Xcode.

**Screenshots**
![Screen Shot 2021-08-11 at 9 41 11 PM](https://user-images.githubusercontent.com/18543934/129125559-61b89fe7-ee92-46ee-9aa8-425dcd0a7dff.png)

**Version**
 - OS: Big Sur 11.5.1
 - Xcodes: 1.1.0 (7)

**Comment by MattKiazyk** [comment]
hey @BrentMifsud when you output: `codesign -vv -d /Applications/Xcode-13.0.0-Beta.4.app` what does that output? 

Did you have the same troubles on Beta 5?

**Comment by BrentMifsud** [comment]
I just installed beta 5 and didn't get this issue this time.

**Comment by MattKiazyk** [comment]
Comment via #iosdevelopers Slack ground from Josh Caswell:

> I believe the CoreServiceUIAgent process is responsible for this window; killing it via Activity Monitor might get the window to go away

Which seemed to work.

I'm closing this issue as there's not much we can do about that one. Workaround to stop it is above.
