### ISSUE TITLE
Unable to download Xcode without dev account

### ISSUE THREAD

**Issue by Nikipe** [RobotsAndPencils/XcodesApp#163]
In the latest version it is impossible to download any version of Xcode if the user is not signed into a currently participating developer account.

Up until the last version it was possible to download Xcode without a participating dev. account.
It is possible to download and use both the betas and stable versions of Xcode without a dev account from developer.apple.com

**Version**
 - OS: macOS Monterey 12.0.1
 - Xcodes: 1.2.0

**Comment by Jarboer** [comment]
@MattKiazyk Today was the first time trying out this app but unfortunately, I got the unable to install error message. I don't have the paying membership but I do have the free version. Is this issue still unfixed? I was able to install it from Apple's developer website under More by clicking View Details on the latest Xcode version. If I can install it from Apple there then why would it not work from the API?

**Comment by Jarboer** [comment]
@MattKiazyk It works, thanks! This is going to be so nice to use to update Xcode!
