### ISSUE TITLE
Unable to install Xcode 13.1

### ISSUE THREAD

**Issue by vpilkevych** [RobotsAndPencils/XcodesApp#164]
**Describe the bug**
The app gives an error in attempt to install Xcode 13.1 on Mac mini M1, although it works on different Intel machines.

**To Reproduce**
1. Press the "Install" button in order to begin Xcode 13.1 installation.
2. The app shows the error message.

**Expected behavior**
The app installs Xcode 13.1.

**Screenshots**
![Screenshot 2021-10-27 at 11 08 22](https://user-images.githubusercontent.com/920844/139036265-ca268e38-24fc-4e56-9524-9c55f5374013.png)

**Version**
 - OS: 11.6, Mac mini M1
 - Xcodes: 1.2.0 (8)

**Comment by qyzdo** [comment]
I wasn't logged in and I had the same error. I found that https://appstoreconnect.apple.com/olympus/v1/session is returning unauthorized status and xcodes had a problem parsing this response.

**Comment by vpilkevych** [comment]
@qyzdo you're completely right, today I decided to give it one more try and found out that I was not logged in. I am sorry, my bad. Closing the issue. @MattKiazyk maybe it'd be better if the app tells the user to log in.

**Comment by qyzdo** [comment]
@vpilkevych you are absolutely right, I created fix for this https://github.com/RobotsAndPencils/XcodesApp/pull/165
