### ISSUE TITLE
Unable to install Xcode

### ISSUE THREAD

**Issue by dmkryzh** [RobotsAndPencils/XcodesApp#169]
**Describe the bug**
After clicking on install button, popup with error is shown

**To Reproduce**

1. Open app
2. Click on install button (any Xcode version)

**Expected behavior**
Xcode is starting to download

**Screenshots**
<img width="259" alt="image" src="https://user-images.githubusercontent.com/77922153/141238456-362064dc-ab04-4ebe-a40d-e3d7bf51afcd.png">

**Version**
 - OS: 11.6
 - Xcodes: 12.5.1 (current version)

**Comment by devshiye** [comment]
I have the same problem as you, but when I click Settings and log in to my Apple ID, it can be downloaded normally.

**Comment by paulofierro** [comment]
I had the same issue and came here to file a bug. Maybe the app should check if the user is logged in first, and report that as the error instead.

**Comment by MattKiazyk** [comment]
There's some fixes coming in #168  that should help this and give proper errors on what's happening.

**Comment by 0x8FF** [comment]
Still facing this issue on macOS 12.1, and I'm logged into into my Apple ID

**Comment by MattKiazyk** [comment]
@shulkk @dmkryzh 1.3.1 was released and fixes a few issues around parsing. I'm going to close this issue, but if the issue still persist, please open a new issue and we'll take a look
