### ISSUE TITLE
Allow Log in with Federated Apple ID

### ISSUE THREAD

**Issue by radloffl** [RobotsAndPencils/XcodesApp#172]
**Tell us how we can improve Xcodes**
At larger organizations that have enrolled in the [Federated Authentication](https://support.apple.com/guide/apple-business-manager/intro-to-federated-authentication-axmb19317543/web) it's not possible to log in to Xcodes. 

**Is your feature request related to a problem? Please describe.**
Unable to log in with federated Apple ID
![image](https://user-images.githubusercontent.com/14222496/145278298-dcd6dd65-44ec-4a2a-9aca-b6ea92e8f563.png)

**What would you like to see? How would you like it to work?**
It'd be good to check if the email address is enrolled in federated authentication first and redirect to the IDP.

**Comment by radloffl** [comment]
Did some playing around with `curl` and figured out the path used to identify/initiate federated account log in. I replaced tokens and email addresses with examples for privacy.

### Example of account without federation
```shell
$ curl -H "Accept: application/json, text/javascript" -H "Content-Type: application/json" -H "X-Requested-With: XMLHttpRequest" -H "X-Apple-Widget-Key: < itcServiceKey >" -d '{ "accountName": "nonfederatedappleid@gmail.com", "rememberMe": "true" }' -X POST "https://idmsa.apple.com/appleauth/auth/federate" 
{
  "showFederatedIdpConfirmation" : false,
  "federated" : false
} 
```
### Example of account with federation (Microsoft is IDP in this case)
```shell                                                                                                                                                                                                           $ $ curl -H "Accept: application/json, text/javascript" -H "Content-Type: application/json" -H "X-Requested-With: XMLHttpRequest" -H "X-Apple-Widget-Key: < itcServiceKey >" -d '{ "accountName": "employee@bigcompany.com", "rememberMe": "true" }' -X POST "https://idmsa.apple.com/appleauth/auth/federate"
{
  "federatedIdpRequest" : {
    "idPUrl" : "https://login.microsoftonline.com/common/saml2?login_hint=employee@bigcompany.com",
    "requestParams" : {
      "SAMLRequest" : "<base 64 encoded SAML string>",
      "RelayState" : "<base 64 encoded SAML string>",
      "AccountName" : "employee@bigcompany.com"
    }
  },
  "federatedAuthIntro" : {
    "orgType" : "enterprise",
    "orgName" : "Big Company Corporation",
    "accountManagementUrl" : "https://login.microsoftonline.com",
    "idpName" : "https://login.microsoftonline.com",
    "idpUrl" : "https://login.microsoftonline.com"
  },
  "showFederatedIdpConfirmation" : true,
  "federated" : true
}
```

**Comment by radloffl** [comment]
After some more playing and reading the [SAML spec](http://docs.oasis-open.org/security/saml/v2.0/saml-bindings-2.0-os.pdf) if federated, the next step would be to do an HTTP `GET` to the `idPUrl` with query parameters for the `requestParams` (`SAMLRequest` base 64 decoded to get XML -> deflated -> base64 encoded -> URL encoded, `RelayState` and `AccountName` are just passed through as query parameters URL encoded)

**Comment by radloffl** [comment]
[Apple.paw.txt](https://github.com/RobotsAndPencils/XcodesApp/files/8848661/Apple.paw.txt)

**Comment by ursforrer** [comment]
Is there any plan to support the feraded apple id for xcodes?

**Comment by MattKiazyk** [comment]
As of v1.8 we no longer require apple accounts to download Xcode.  🥳 I'm going to close this issue as I believe the main concern was around username/password.

**Comment by alteral** [comment]
Hey @MattKiazyk, I'm on v.1.9, but `Xcodes` says that I'm not authorised to download/install Xcode 🤔
![Screen Shot 2022-12-15 at 12 06 40 PM](https://user-images.githubusercontent.com/20794991/207855290-71801652-587e-4148-8701-640e577ac43a.png)

**Comment by MattKiazyk** [comment]
@alteral. Did you sign in to your apple account in Xcode? Tap the 
<img width="77" alt="image" src="https://user-images.githubusercontent.com/1119565/207893823-53229a02-31c0-425e-aad7-ee7710fb9003.png">
icon

**Comment by alteral** [comment]
@MattKiazyk, I'm logged in in `Xcode`, but not in `Xcodes` because it does not allow to log in with Federated Apple ID. This is the screenshot after tapping on the icon: 
<img width="504" alt="Screen Shot 2022-12-15 at 3 41 42 PM" src="https://user-images.githubusercontent.com/20794991/207903824-0d30c9b3-e844-4193-be6a-fa4f3ab44f33.png">

**Comment by dazigna** [comment]
Any updates on this thread ? this would unblock all account managed by a company

**Comment by jschear** [comment]
Could this be reopened? I'm interested in contributing.

**Comment by gabriellet** [comment]
This still seems to be an issue. Can we reopen it?

**Comment by tejassharma96** [comment]
> As of v1.8 we no longer require apple accounts to download Xcode. 🥳 I'm going to close this issue as I believe the main concern was around username/password.

No longer requiring apple accounts was fairly quickly rolled back so it's disappointing that this issue has stayed closed

**Comment by jschear** [comment]
I took a stab at this in https://github.com/XcodesOrg/XcodesApp/compare/main...jschear:XcodesApp:js/federated_sso. I am able to initiate the SSO flow in a browser window, but redirecting back to the Xcodes app isn't working yet.

The account I'm attempting to get working is using Okta SSO -- I believe the `FederatedRequestParams` [portion of the response](https://github.com/XcodesOrg/XcodesApp/compare/main...jschear:XcodesApp:js/federated_sso#diff-5eba00295643334abef92e9a8c0f41b9e9affe7d37ffb097d11527611ce63b98R684-R691) would be different for a SAML setup.
