### ISSUE TITLE
Faster XIP Extraction

### ISSUE THREAD

**Issue by WillBishop** [RobotsAndPencils/XcodesApp#176]
**Tell us how we can improve Xcodes**

More of a question, does Xcodes use the command line `xip` tool? I read [this Twitter thread](https://twitter.com/_saagarjha/status/1481353292164698112?utm_campaign=iOS%2BDev%2BWeekly&utm_medium=email&utm_source=iOS%2BDev%2BWeekly%2BIssue%2B541) and they describe how `.xip` can be faster extracted. It seems to relate to not using Archive Utility, which I *believe* Xcodes uses, unless I'm mistaken?

**What would you like to see? How would you like it to work?**

I'd love some confirmation on whether or not Xcodes uses the `xip` tool or Archive Utility?

**Comment by MattKiazyk** [comment]
Hey @WillBishop 

Yep Xcodes uses `xip` command line when extracting. You can see that here: https://github.com/RobotsAndPencils/XcodesApp/blob/83fa00b21fbe54594d5a1a37ef7a4cf830488cee/Xcodes/Backend/Environment.swift#L28 

If there is anything that we could ever do to make that process faster we absolutely would add it in.

**Comment by mackoj** [comment]
You could try this https://github.com/saagarjha/unxip

**Comment by MattKiazyk** [comment]
😉 

https://github.com/RobotsAndPencils/XcodesApp/pull/179

**Comment by MattKiazyk** [comment]
This is available to test on 1.3.0 (in prerelease) https://github.com/RobotsAndPencils/XcodesApp/releases/tag/v1.3.0b10

Make sure your `Include prerelease app versions` is checked

![image](https://user-images.githubusercontent.com/1119565/152923264-bc0d045e-614c-4bd8-9539-140193d70ab1.png)

**Comment by mackoj** [comment]
@MattKiazyk thanks I'll try it

**Comment by MattKiazyk** [comment]
Closing this ticket as the faster unxip experiment is no in general release as of 1.3.1
