### ISSUE TITLE
Xcodes does not recognize Apple Developer Registration

### ISSUE THREAD

**Issue by ryanvidal** [RobotsAndPencils/XcodesApp#178]
**Describe the bug**
Despite being registered as an Apple developer, and being able to download Xcode manually, Xcodes complains:
```
You are not registered as an Apple Developer.  Please visit Apple Developer Registration. https://developer.apple.com/register/
```
Going to that link just gives me the getting started guide from Apple - I don't actually have to do anything else on the site.

**To Reproduce**
* Sign into Apple account in Xcodes
* Try to download a version of Xcode
* Get failure notification

**Expected behavior**
Successfully download the version of Xcode selected

**Version**
 - OS: 12.2
 - Xcodes: 1.2.0 (8)

**Comment by MattKiazyk** [comment]
Hi @ryanvidal thanks for the issue. 

This issue should be fixed via https://github.com/RobotsAndPencils/XcodesApp/pull/168 but just hasn't been released yet. I will do my best to get on it this week.

**Comment by ryanvidal** [comment]
@MattKiazyk Ah, I see, I didn't see that issue when I looked. I appreciate it!

**Comment by ryanvidal** [comment]
@MattKiazyk Any movement on a release? I'm wanting to install 13.3 on my machine soon and hoping to use Xcodes!

**Comment by MattKiazyk** [comment]
Sorry @ryanvidal been busy - you can install the pre-release which should get around your issue.

**Comment by ryanvidal** [comment]
🤦🏼 Sorry, I didn't even think to check if there was a pre-release version. Thanks for pointing it out (and for the app in general)!

**Comment by zealforbeing** [comment]
I get this issue in v1.5.0. And v1.4.0 is OK!

**Comment by MattKiazyk** [comment]
@zealforbeing hmm. 

If possible, it would help if you could downloading the project and run it in debug mode. The big thing is what the responses from log in come back as. Looks like we're not handling certain cases very well.
