### ISSUE TITLE
Add option to always have a version named "Xcode.app" on activate

### ISSUE THREAD

**Issue by Jeehut** [RobotsAndPencils/XcodesApp#180]
**Tell us how we can improve Xcodes**
This app is amazing and I use it all the time. The only thing I need to do manually right now is after upgrading to a new stable release and making it the active one, to rename it so it does not have the version in its name, which I don't want to have for the latest stable release.

**Is your feature request related to a problem? Please describe.**
I know that "make active" is the right approach, but some tools expect to have a path just called `Xcode.app` and therefore it's safer to have the latest stable just called that. See https://github.com/Flinesoft/BartyCrouch/issues/179 for example.

**What would you like to see? How would you like it to work?**
Besides the existing "Active" button, there could also be a "Default name" button. Or alternatively, there could be an option in the preferences stating something like "Remove version suffix from currently active Xcode apps name".

**Comment by ptrkstr** [comment]
This is an excellent idea. I also would feel more comfortable if the selected Xcode was renamed to Xcode.app (though I have no tangible evidence right now for why).

**Comment by Jeehut** [comment]
@pratikzora It's not just about "feeling comfortable", it is a real issue because there's many tools etc. that depend on the exact path `Xcode.app`, see [this issue](https://github.com/Flinesoft/BartyCrouch/issues/179) users of my command line tool reported and [the workaround](https://github.com/Flinesoft/BartyCrouch/issues/179#issuecomment-1006499418) which clearly indicates that Apples [swift-syntax](https://github.com/apple/swift-syntax) library depends on that path. And while I don't remember all the specifics, I did encounter other issues without an Xcode named exactly `Xcode.app` as well, so it's definitely a good idea to always have a current Xcode named without a version suffix.

**Comment by Jeehut** [comment]
And here's another reason why keeping the name `Xcode.app` is important (basically, for Xcode Extensions to work):
https://stackoverflow.com/a/60431819/3451975

**Comment by MattKiazyk** [comment]
Thanks for the suggestion and the conversation.

I know even personally I've hit issues where we use a naming convention different then say Github Action environments. We call it `Xcode-13.2.0` where Github names it `Xcode-13.2`. Using any tool inside those environments that require `Xcode.app` would run into the same issue since Github doesn't have a single `Xcode.app` 

I would suggest that any tools shouldn't be looking at exactly for `xcode.app`. In the instance of `Library not loaded: @rpath/lib_InternalSwiftSyntaxParser.dylib` I would suggest building the tool with that library baked in. 

You can see examples of how other tools have done it - https://github.com/uber/needle/pull/367

As far as Xcode extensions, I'd have to look into how they are looking to see where the app is or where they store the extension files.

**Comment by Jeehut** [comment]
@MattKiazyk Thank you for the suggestion, I will try to have a look into it for BartyCrouch. And that's probably what all tools should do. But I would like to keep the name `Xcode.app` anyway, even if it's just for the Xcode Extensions to work.

**Comment by muescha** [comment]
i also have the problem that it shows my xcodes as outdated in MAS - but i already have installed the new version with `xcodes`

**Comment by federicopolesello** [comment]
Yeah, it would be great if the active version could be rename with a default name `Xcode.app`

**Comment by MattKiazyk** [comment]
Cheers @Jeehut - Thanks for the example of what you're wanting to do.

**Comment by chickdan** [comment]
I'm in agreement with Jeehut, Xcodes is "marketed" as a management tool for multiple version and not necessarily a launcher that you have to use if you don't want to to use search every time you attempt to open Xcode. Like Jeehut I keep Xcode on my dock for quick access, having the Active version renamed would be delightful!

**Comment by MattKiazyk** [comment]
I've made a PR that implements renaming to `Xcode.app` on Select. I'll give it a few days to look over and merge it in, but should be available next release. 

Thanks for the suggestion.

**Comment by MattKiazyk** [comment]
@chickdan @Jeehut @ptrkstr 

This enhancement is now available in 1.7. Please test it out, and let me know if there are any issues.

**Comment by Jeehut** [comment]
It is unchecked:
![Screen Shot 2022-08-09 at 15 27 23](https://user-images.githubusercontent.com/6942160/183658805-2e57cc91-8b3b-4aa2-b323-86d7617d49b0.png)
![Screen Shot 2022-08-09 at 15 27 37](https://user-images.githubusercontent.com/6942160/183658931-41eed4af-350f-4b31-8f70-85bdb9b75aa8.png)

**Comment by Jeehut** [comment]
Note that it unchecks (and additionally disables) automatically when I switch to "Always rename to Xcode.app" even when it's checked before. When I then go back to "Keep name as Xcode-X.X.X.app" it stays unchecked (but enables). Maybe there's something wrong with the persistence as you seem to be right that it looks like it's turned on based on the error message ...

**Comment by MattKiazyk** [comment]
@Jeehut can you create a new ticket and I will look into it.
