### ISSUE TITLE
Experiment Icon is SF 3.0 so doesn't work on < OS 12.0

### ISSUE THREAD

**Issue by MattKiazyk** [RobotsAndPencils/XcodesApp#182]
**Describe the bug**
Find a different icon so that it shows up for users < 12.0 (users that don't have SF3.0)

<img width="852" alt="image" src="https://user-images.githubusercontent.com/1119565/154299630-9f00862a-90fc-4ec4-9683-9a2ce5e28cef.png">

**To Reproduce**
Run pre release on Mac OS 11.X - experiment icon doesn't show as per screenshot

**Expected behavior**
The icon should show up for all users.

**Comment by DD-P** [comment]
Rather than a different icon, I think you should be able to export the testtube.2 symbol from SF Symbols and add it to your assets as a fallback.

**Comment by MattKiazyk** [comment]
Fixed in 1.3.1
