### ISSUE TITLE
Specify a separate Xcode installation folder in Prefs

### ISSUE THREAD

**Issue by tengelmeier** [RobotsAndPencils/XcodesApp#183]
**Tell us how we can improve Xcodes**
Specify a separate Xcode installation folder in Prefs

**Is your feature request related to a problem? Please describe.**
TimeMachine takes ages to backup the myriad of files from Xcode. I't like to exclude a top level Xcode installations folder from Backup.

**What would you like to see? How would you like it to work?**
Specify an folder as pref in Xcodes where all the Xcode variants get downloaded to..

**Comment by MattKiazyk** [comment]
Closing this issue. Tracking via https://github.com/RobotsAndPencils/XcodesApp/issues/148
