### ISSUE TITLE
Unable to install Xcode

### ISSUE THREAD

**Issue by Aayush9029** [RobotsAndPencils/XcodesApp#185]
**Describe the bug**
I did a clean install of macOS Monterey  12.2.1 (21D62) and tried to use XcodesApp to download and install Xcode. Json Decoding error came up! 

```
The operation couldn't be completed.
(Error.dataCorrupted (Swift.DecodingErro
.Context (codingPath: I.
debugDescription: "The given data was
not valid JSON.", underlyingError:
Optional (Error
Domain=NSCocoaErrorDomain
Code=3840 "Invalid value around line 1,
column 0"
Userinfo=(NSDebugDescription=Invalid
value around line 1, column 0.,
NSJSONSerializationErrorlndex=0}))))
```

**To Reproduce**
- Clean install macOS
- Downloaded the latest XcodesApp **v1.2.0**
- Click Install 

**Expected behavior**
- Start downloading / installing Xcode

**Screenshots**
![Screen Shot 2022-02-26 at 8 23 56 PM](https://user-images.githubusercontent.com/43297314/155866575-e88e35bb-6f62-451e-a338-144cd3413eb3.png)

**Version**
 - OS:  12.2.1 
 - Xcodes: v1.2.0

**Comment by MarcoEidinger** [comment]
I encountered the same issue and thanks to [this tip](https://twitter.com/xcodesapp/status/1498800084619776002) I was able to download Xcodes pre release version [1.3.0](https://github.com/RobotsAndPencils/XcodesApp/releases/tag/v1.3.0b10).

This version has a new enhancement:
- Show a message when user is not authorized yet (https://github.com/RobotsAndPencils/XcodesApp/pull/165) @qyzdo

For me it surfaced the error that I was not signed-in :) you want to check this in your Xcodes preferences

**Comment by Aayush9029** [comment]
You're totally correct! This was my first time using the app and was unaware of authorization requirement! *which totally makes sense* granted an initial pop-up or helpful error would be nice. 

The merge you mentioned seems to fix this issue. Cheers!
