### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by ayafayad** [RobotsAndPencils/XcodesApp#188]
**Describe the bug**
When I downloaded Xcodes App, I tried to install Xcode 13.2.1 but I kept getting an error which I later found out that I need to login in order to stop their error from happening but when I try to login, I also receive an error and in the error it states that if this problem persists to submit a Bug report

**To Reproduce**
1. Download Xcodes App 
2. Click on the login button 
3. Enter my credentials 
4. An error occurs that states "Received an unexpected status code: 412. If you continue to have problems, please submit a bug report in the help menu" 

**Expected behavior**
I will be logged into my account to start Xcode download

**Screenshots**
<img width="254" alt="Screen Shot 2022-03-06 at 11 54 19 AM" src="https://user-images.githubusercontent.com/25375353/156918400-0c8ee4fd-f556-4223-95e0-3f1801587b38.png">
<img width="899" alt="Screen Shot 2022-03-06 at 11 49 52 AM" src="https://user-images.githubusercontent.com/25375353/156918401-b73b98fe-830a-4ab9-b2cf-1bcf093c1212.png">

**Version**
 - OS: 12.2
 - Xcodes: 1.2.0

**Comment by eeeyyeeezz** [comment]
Same, look forward to fix this

**Comment by rewgoes** [comment]
Same here

**Comment by MattKiazyk** [comment]
@ayafayad @eeeyyeeezz @rewgoes version 1.3.1 should fix a lot of these errors. I'm going to close this issue, but if you get any more similar issues, please let me know in this issue.

Thanks!

**Comment by dkorduban** [comment]
I encounter a similar issue with v. 1.4.0 (12)

**Comment by MattKiazyk** [comment]
@dkorduban can you open up a new issue with information. If you have network logs that would be awesome as well
