### ISSUE TITLE
Can't authorize

### ISSUE THREAD

**Issue by eeeyyeeezz** [RobotsAndPencils/XcodesApp#189]
Good day everyone.

When trying to authorize get an error (get this error with every version, tried 3-4 different releases) "Received an unexpected status code: 412. If you continue to have problems, please submit a bug report in the Help menu"

How to fix this? Thanks.

(i do not have developer account)
<img width="277" alt="Снимок экрана 2022-03-11 в 11 14 58" src="https://user-images.githubusercontent.com/68189276/157829167-b309c266-2be4-47d0-9f0c-b92157b1279f.png">

**Comment by gkoca** [comment]
login [https://developer.apple.com/account](https://developer.apple.com/account) and confirm agreement then try to authorize on the app.

**Comment by MattKiazyk** [comment]
Hi @eeeyyeeezz unfortunately you do need an apple id that is set up as a developer account in order to download Xcode directly. This is totally free and no cost to you, so you don't need a paid developer.
