### ISSUE TITLE
Unhelpful error message on authentication failure

### ISSUE THREAD

**Issue by gredman** [RobotsAndPencils/XcodesApp#192]
**Describe the bug**

Launching Xcodes works as expected and shows a list of available Xcode versions. However clicking "install" on any shows the following error:

`The operation couldn’t be completed. (Error.dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "Invalid value around line 1, column 0." UserInfo={NSDebugDescription=Invalid value around line 1, column 0., NSJSONSerializationErrorIndex=0}))))`

Trying again with Proxyman intercepting the network requests, I see a 401 from https://appstoreconnect.apple.com/olympus/v1/session

My keychain contents were deleted a few days ago -- I presume that is why authentication is failing.

**To Reproduce**

1. Launch Xcodes
2. Cilck "install" on any build version

**Expected behavior**

The download begins, or an error message appears stating that an authentication error has occurred.

**Screenshots**

<img width="911" alt="Screen Shot 2022-03-16 at 12 33 49" src="https://user-images.githubusercontent.com/608139/158489791-d813abe2-3c8e-4cc7-84d6-5816162dd1a5.png">
<img width="1234" alt="Screen Shot 2022-03-16 at 12 41 28" src="https://user-images.githubusercontent.com/608139/158490026-8f8504e8-73dc-4498-b8c9-735bdc9d7fe2.png">

**Version**
 - OS: 12.0.1 (21A559)
 - Xcodes: 1.2.0 (8)

**Comment by gredman** [comment]
Re-entering my Apple credentials makes the download work.

**Comment by ChristopherDrum** [comment]
I can confirm the same. Entering Apple credentials in that little "Apple ID" silhouette icon worked. But entering into that field was difficult. It seemed unusually slow to take input, and it tried to pop up a window, but it was only the outline of a window and it prevented me from putting in information. Clicking into the password field cleared this, kind of. It reappeared when I clicked into the username field, but this time the username field accepted input properly. A colleague is finding that the Apple 2FA doesn't accept his authentication code, but I didn't have this issue.

**Comment by vilanovi** [comment]
worked for me after entering apple credentials.

**Comment by MattKiazyk** [comment]
@gredman going to close this issue as newer 1.3.1 version handles these errors a bit better which can give you a better indication of what could be wrong.

Thanks!
