### ISSUE TITLE
When opening an installed xcode release, I get error alert: "Loading a plug-in failed"

### ISSUE THREAD

**Issue by Caleb-Bolton** [RobotsAndPencils/XcodesApp#204]
**Describe the bug**
When attempting to open Xcode release 13.2.1 (already installed) in the xcodes GUI, an error window pops up saying:
"Loading a plug-in failed.
The plug-in or one of its prerequisite plug-ins may be missing or damaged and may need to be reinstalled."

I have the xcodes helper installed if that matters.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/23207563/164285826-047015ee-919d-43b8-9ac8-063280769f56.png)

**Version**
 - OS: 12.3.1
 - Xcodes: 1.4.0

**Comment by MattKiazyk** [comment]
Hi @Caleb-Bolton - Curious on a few fronts:
- Does opening through the regular way through Finder give you the same error? 
- Do you have any Xcode plugins installed?

**Comment by Caleb-Bolton** [comment]
I forgot what it was, but a popup saying a process started (during installation or startup) was shown and I believe I cancelled it as I thought it was unrelated to Xcodes. I think this is what caused the issue, because I either started it up or reinstalled and let that process finish and I had no more problems.
