### ISSUE TITLE
Show download progress as `X.XX GB of Y.YY GB`

### ISSUE THREAD

**Issue by tinder-tannerbennett** [RobotsAndPencils/XcodesApp#207]
Currently the only progress indicator we have is the circle progress bar, which is not great.

**Comment by MattKiazyk** [comment]
hi @tinder-tannerbennett, we show this information on the info bar. Tap the ℹ️ icon on the top bar.

 Please make sure you have selected `aria2` as your downloader: 
<img width="535" alt="image" src="https://user-images.githubusercontent.com/1119565/164724037-4bc417e4-37ba-4e7e-a701-fb5e03920327.png">

<img width="305" alt="image" src="https://user-images.githubusercontent.com/1119565/164723931-4ba75aac-f1cd-4d8d-9b07-36bb685bcd2d.png">
