### ISSUE TITLE
always show "Unable to install Xcode"

### ISSUE THREAD

**Issue by zrx89757** [RobotsAndPencils/XcodesApp#211]
**Describe the bug**
always show "Unable to install Xcode"

**To Reproduce**
just downloaded xcodes.app, sign in my apple id, selected a version, click INSTALL

**Expected behavior**
install the target version of xcode 

**Screenshots**
<img width="895" alt="image" src="https://user-images.githubusercontent.com/15121098/165034152-f4889c6f-28a2-4e7a-8d44-616340d48af8.png">

**Version**
 - OS: macOS Monterey 12.0.1
 - Xcodes: 1.4.0(12)

**Comment by MattKiazyk** [comment]
Hi @zrx89757 Can you make sure you're logged in properly via the Open Login option:

<img width="80" alt="image" src="https://user-images.githubusercontent.com/1119565/165211303-81f6d0bf-2a7f-4526-b4c6-ce47a8fddf16.png">

Usually download issues are a result of that.

**Comment by iMokhles** [comment]
Check my comment here:
https://github.com/RobotsAndPencils/XcodesApp/issues/215#issuecomment-1117091473

**Comment by MattKiazyk** [comment]
As of v1.8 we no longer require apple accounts to download Xcode so these errors won't show up anymore 🥳
