### ISSUE TITLE
Can not install the privileged helper

### ISSUE THREAD

**Issue by patrick-fu** [RobotsAndPencils/XcodesApp#213]
**Describe the bug**

I install the Xcodes app via homebrew, and the Xcodes version is 1.4.0 (12)

After the Xcode installed , it failed in the step of switch Xcode version. 

**Screenshots**

<img width="791" alt="Screenshot 2022-04-24 at 19 14 09" src="https://user-images.githubusercontent.com/20736775/164973731-9d7ee9f4-c4ed-48bf-ac99-088b0634fb53.png">
<img width="791" alt="Screenshot 2022-04-24 at 19 14 16" src="https://user-images.githubusercontent.com/20736775/164973734-809edf2e-f6d4-475b-9ea6-ff22416bb56d.png">

**Version**
 - OS: 12.3
 - Xcodes: 1.4.0 (12)

**Comment by kayaYuan** [comment]
I use `sudo launchctl enable system/com.robotsandpencils.XcodesApp.Helper`  fix it
maybe you can try it

this code can list the disabled services
`launchctl print-disabled system`

**Comment by patrick-fu** [comment]
> I use `sudo launchctl enable system/com.robotsandpencils.XcodesApp.Helper` fix it maybe you can try it
> 
> this code can list the disabled services `launchctl print-disabled system`

🎉 Wow it worked, thanks! @kayaYuan
