### ISSUE TITLE
Impossible to install any Xcode version

### ISSUE THREAD

**Issue by antoniogermano** [RobotsAndPencils/XcodesApp#215]
**Describe the bug**
XcodesApp is unable to install any Xcode version

**To Reproduce**
I've installed XcodesApp with Homebrew, authorized the helper app, and set up a valid Apple ID. I tried using aria2 and NSURLSession. I can't install any versions of Xcode at all. I always get this error message:
<img width="293" alt="image" src="https://user-images.githubusercontent.com/816290/166107199-b82b25e2-5918-4c9c-8d84-644c776435b7.png">

I don't know if it makes any difference but I already have 3 Xcode versions manually installed by myself
<img width="293" alt="image" src="https://user-images.githubusercontent.com/816290/166107369-1f1ef63d-f65a-4ed9-bf0c-dce79662aa27.png">

**Expected behavior**
The desired Xcode version should be installed.

**Version**
 - OS: M1 Max 12.3.1 (21E258)
 - Xcodes: 1.4.0 (12)

**Comment by antoniogermano** [comment]
Possibly related to #211 although I have provided more information than the other report (and yes, the "show Apple ID" button presents my e-mail)

**Comment by iMokhles** [comment]
if you are already logged in you have to agree Apple Developer Agreement 
go to
https://xcodereleases.com/
click on download any xcode version 
login with your apple developer account
agree the Apple Developer Agreement
it will start downloading the Xcode version you want ( YOU CAN CANCEL IT )
Go BACK to Xcodes.app ( and it will work fine )

**Comment by kupilot** [comment]
Did all that, still unable to install.

**Comment by davidAg9** [comment]
my installs but the unarchiving stage has taken me 2 days now on my 2020 MacBook Pro , I don't know if it has to do with storage or something else .... Does Xcodesapp report low storage if there is ?

**Comment by ama-non** [comment]
> if you are already logged in you have to agree Apple Developer Agreement go to https://xcodereleases.com/ click on download any xcode version login with your apple developer account agree the Apple Developer Agreement it will start downloading the Xcode version you want ( YOU CAN CANCEL IT ) Go BACK to Xcodes.app ( and it will work fine )

works fine,  thank u

**Comment by MattKiazyk** [comment]
As of v1.8 we no longer require apple accounts to download Xcode so these errors won't show up anymore 🥳
