### ISSUE TITLE
Login fails and return error code as 412

### ISSUE THREAD

**Issue by whatisyournickname** [RobotsAndPencils/XcodesApp#216]
**Describe the bug**
Login fails and return error code as 412

**To Reproduce**
Log in, type in email and password, login fails

**Expected behavior**
Log in, type in email and password, login successful

**Screenshots**

**Version**
 - OS:  Monterey 12.1
 - Xcodes: 1.4.0
<img width="903" alt="Screenshot 2022-05-02 at 2 34 51 AM" src="https://user-images.githubusercontent.com/43547035/166159703-24870fbd-8bcf-45f6-a832-420e1556979a.png">

**Comment by MattKiazyk** [comment]
Hi @whatisyournickname 

Did this ever work for you? When logging into say developer.apple.com does the 2fa work?

**Comment by zocario** [comment]
Hi, I'm having the exact same issue, I'm unable to login within the App to download new versions of Xcode 🙈

**Comment by MattKiazyk** [comment]
@zocario if you log into developer.apple.com does it work?

**Comment by MattKiazyk** [comment]
As of v1.8 we no longer require apple accounts to download Xcode so these errors won't show up anymore 🥳
