### ISSUE TITLE
Improve experience when an error requires the user to authenticate

### ISSUE THREAD

**Issue by interstateone** [RobotsAndPencils/XcodesApp#22]
Currently:

1. Sign out
2. Refresh
3. Note that an invalid session error alert is shown, as well as the sign in UI in preferences

Instead of showing both of these at the same time without explanation, we probably want to do something like one of these options:

- Show the error alert with a Sign In button that shows the sign in UI. There should be a way to indicate that certain errors require the user to sign in. I prefer this option.
- Skip the error alert, and only show the sign in UI
- Only show the error alert, and instruct the user to sign in in preferences.

**Comment by fjcaetano** [comment]
On the same topic, sign in is hidden within the app's preferences. I tried using it for the first time and it kept failing with the `Your authentication session is invalid. Try signing in again.` message without any indication of how to solve it. I had to get into the code to find out that the app had authentication and it was handled within the preferences.

If the app requires logging in to work, why not ask it on launch?
