### ISSUE TITLE
Support Apple app-specific password to login

### ISSUE THREAD

**Issue by spike-hue** [RobotsAndPencils/XcodesApp#223]
**Describe the bug**
I created an app-specific password on https://appleid.apple.com. When I try to use the password, it fails. 

Here are docs on app specific passwords: https://support.apple.com/en-us/HT204397

**To Reproduce**
1. Create app specific password at https://appleid.apple.com
2. Try to login Xcodes.app

**Expected behavior**
Can log in.

**Screenshots**
<img width="415" alt="Screen Shot 2022-05-14 at 1 14 22 PM" src="https://user-images.githubusercontent.com/10701375/168441951-a4579022-2578-49e6-899a-2f933e794065.png">

**Version**
 - OS: Monterey 12.3.1
 - Xcodes: 1.5.0 (13)

**Comment by MattKiazyk** [comment]
hi @spike-hue we currently don't support this mechanism to log in. The way the app downloads the xip files, I'm not even sure if this is possible, but I've changed this ticket to an enhancement and will keep it open.

**Comment by spike-hue** [comment]
That's unfortunate. For security purposes, Apple recommends not freely inputting your Apple ID password into applications. While this app may be trustworthy, others keep your password for the wrong reasons. I really like the safety of using the app-specific passwords.

Would be great for your team investigates this!

**Comment by alkozin** [comment]
Waiting for app-specific password support too.

**Comment by MattKiazyk** [comment]
As of v 1.8.0 we no longer require any passwords to download Xcode 🥳

**Comment by alkozin** [comment]
Don't work in 1.9.0... 😞

<img width="1077" alt="Screenshot 2022-12-19 at 14 32 15 1" src="https://user-images.githubusercontent.com/2376017/208371423-72c5c7b8-b1ea-4295-8db2-d111d7d0415e.png">
