### ISSUE TITLE
App crashes when User cancels the Sign In

### ISSUE THREAD

**Issue by jakubziembinski** [RobotsAndPencils/XcodesApp#227]
**Describe the bug**
The app crashes when the User taps "Cancel on the "Enter 6 digit..." screen.

**To Reproduce**
1. Select Sign In button
2. Enter correct credentials
3. Select "Next"
4. The Apple sign in prompt will be pushed on your devices - it doesn't matter what you select.
5. On the "Enter 6 digit code..." screen select "Cancel"

**Expected behavior**
The "Enter 6 digit..." screen is closed and sign in process is gracefully ended.

**Version**
 - OS: 12.3.1 (21E258)
 - Xcodes: 1.5.0

**Comment by MattKiazyk** [comment]
Thanks @jakubziembinski for sending this in - easily duplicated!
