### ISSUE TITLE
bug install xcode

### ISSUE THREAD

**Issue by cuongtq4998** [RobotsAndPencils/XcodesApp#231]
**Describe the bug**
cannot install xcode ver 13.2.1

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="625" alt="image" src="https://user-images.githubusercontent.com/54018352/169577769-99011beb-ae98-4b61-9a14-fee265c882c4.png">

**Version**
 - OS: 12.3
 - Xcodes: 13.2.1

**Comment by MattKiazyk** [comment]
@cuongtq4998 can you try logging out and logging back into your Apple account on Xcodes.

**Comment by cuongtq4998** [comment]
@MattKiazyk  Did all that, still unable to install. :(((

**Comment by cuongtq4998** [comment]
still show alert as this

> **Describe the bug** cannot install xcode ver 13.2.1
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** <img alt="image" width="625" src="https://user-images.githubusercontent.com/54018352/169577769-99011beb-ae98-4b61-9a14-fee265c882c4.png">
> 
> **Version**
> 
>     * OS: 12.3
> 
>     * Xcodes: 13.2.1

**Comment by MattKiazyk** [comment]
@cuongtq4998  Do you have a proxy app that you can log the api response? The json that's being returned from apple is not what xcodes it's expecting and we are showing the generic error message.
