### ISSUE TITLE
Unable to unzip when Experimental unzip is checked

### ISSUE THREAD

**Issue by devlinlin** [RobotsAndPencils/XcodesApp#238]
**Describe the bug**
I found I met some problem installing Xcode when Experimental unzip is checked, it will hang at unzip stage forever, I think I start to get this problem since 2 versions early.
But when I unchecked the Experimental unzip, everything works fine.

**To Reproduce**
It just happens in my Mac, and I didn't see any similar issue in this repo.

**Expected behavior**
Should unzip when Experimental unzip is checked.

**Version**
 - OS: 12.4 (21F79)
 - Xcodes: 1.6.0(14)

**Comment by MattKiazyk** [comment]
Hey @devlinlin 
Sorry to hear about this. just tested on newest 1.6.0 and it seems to be working. The code for unxip is on https://github.com/saagarjha/unxip so if you can try and duplicate manually from the steps there and it still doesn't work, perhaps a bug on that repo. If it works there, let me know. 
Thanks
