### ISSUE TITLE
Xcode 14 beta gives Failed Security assessment error

### ISSUE THREAD

**Issue by MattKiazyk** [RobotsAndPencils/XcodesApp#239]
**Describe the bug**
After downloading, unxipping, and moving to /applications folder Xcode gives  an error:

```
Unable to install Xcode

Failed Security assessment with the following output:

/applications/Xcoce-14.0.0-beta.app: rejected (invalid destination for symbolic link in bundle)
```

Xcodes is failing the call of `spctl --assess --verbose --type execute /applications/Xcoce-14.0.0-beta.app` 

**To Reproduce**
Download Xcode 14 beta 1 - Xcode gives error

**Expected behavior**
Security assessment passes without error

**Screenshots**

**Version**
 - OS: 12.4
 - Xcodes: 1.6

**Comment by orand** [comment]
This just happened to me as well.

**Comment by MattKiazyk** [comment]
Submitted a ~~bug report~~ feedback FB10049201 (spctl assess fails on Xcode 14.0-Beta)

**Comment by orand** [comment]
Yep, installing beta 2 worked perfectly for me.
