### ISSUE TITLE
Xcodes crash on macOS Ventura Beta3

### ISSUE THREAD

**Issue by devlinlin** [RobotsAndPencils/XcodesApp#265]
**Describe the bug**
Xcodes 1.6.0 crash on macOS Ventura beta 3 when open the experiment tab in preference panel.
Also can not open preference panel with the setting button.

**To Reproduce**
video:
https://user-images.githubusercontent.com/19910304/179341452-954f31e5-e7bc-4de1-b55e-b3f44c1b2b37.mov

**Expected behavior**
Should open the preference panel by clicking the setting button.
Should not crash when click the experiment tab in preference panel.

**Screenshots**
video:
https://user-images.githubusercontent.com/19910304/179341452-954f31e5-e7bc-4de1-b55e-b3f44c1b2b37.mov

**Version**
Xcodes version:
<img width="580" alt="截屏2022-07-16 13 34 11" src="https://user-images.githubusercontent.com/19910304/179341555-c00557b7-0085-4075-ac24-36d296955fa4.png">

System information:
![SCR-20220716-iuw](https://user-images.githubusercontent.com/19910304/179341562-ba9fdd8b-b043-4a76-a662-4eb154f2bfe0.png)

**Comment by MattKiazyk** [comment]
Should be fixed via #242 - will be on the next release.
