### ISSUE TITLE
Missing localizations for de_DE

### ISSUE THREAD

**Issue by darthsteff** [RobotsAndPencils/XcodesApp#282]
**Describe the bug**
There seem to be a couple of untranslated strings - indicated by the appearance of their localization key (see attached screenshots)

**To Reproduce**
Change macOS language to German, open the settings page of Xcodes

**Expected behavior**
All strings should be localized. 
I'll gladly provide help if required.

**Screenshots**

**Version**
 - OS: macOS Monterey 12.2.1
 - Xcodes: 1.7.0 (15)
![Bildschirmfoto 2022-08-31 um 15 36 26](https://user-images.githubusercontent.com/171404/187692425-1d04c2c1-f125-482c-8e99-c926cd607dbc.png)

**Comment by MattKiazyk** [comment]
@drct do you have a few minutes to update this?

**Comment by drct** [comment]
@MattKiazyk Sure, I'm on it

**Comment by drct** [comment]
Done

**Comment by MattKiazyk** [comment]
Thanks @drct!
