### ISSUE TITLE
Do not delete the downloaded xip after a download has completed

### ISSUE THREAD

**Issue by groue** [RobotsAndPencils/XcodesApp#286]
**Tell us how we can improve Xcodes**

Hello, what about keeping the downloaded xip files on disk after a download? This could help sharing it with other people on the same LAN.

**Is your feature request related to a problem? Please describe.**

The "problem" is that after a long download has completed, I can't share my downloaded xip with other people in the room.

**What would you like to see? How would you like it to work?**

A solution could be to move the xip in the Trash when a download has completed, instead of deleting it.

This would:

- Prevent the xip from remaining in the "Cache Local" folder (`~/Library/Application\ Support/com.robotsandpencils.XcodesApp`) forever, hidden from user's sight, consuming disk space like a big blob of useless bytes.
- Allow users to easily delete the xip (empty the Trash)
- Allow user to share the xip (move the xip out of the Trash and do whatever they want).

What do you think?

**Comment by MattKiazyk** [comment]
Hey @groue 

Thanks for the suggestion. Xcodes does just move the xip to the trash bin. It doesn't delete it fully. So you could just move that xip out of the trash to whereever you need to so others can use it. 

Please let me know if that answers your question

**Comment by groue** [comment]
Oops, it just looks like I requested a feature that was already implemented 😅

(Just confirmed: a downloaded archive is sitting right in my trash bin)

Thank you for the great app!

**Comment by JJAYCHEN1e** [comment]
Can we just provide an option to not move it to the trash? I checked out my trash, but unfortunately I've cleaned my trash..
