### ISSUE TITLE
Unable to install Xcode (DecodingError)

### ISSUE THREAD

**Issue by oronbz** [RobotsAndPencils/XcodesApp#289]
**Describe the bug**
I've Installed Xcodes from homebrew, signed in with my appleID, trying to install any version gives:
Unable to install Xcode: `Error.dataCorrupted`, `Swift.DecodingError`

(I've tried restarting the app)

**To Reproduce**
1. Install Xcodes from homebrew
2. Sign in
3. install any version

**Expected behavior**
Xcode will be installed

**Screenshots**
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/1288090/189515246-c625d730-d020-44a7-bce9-e649b0b636c2.png">
![image](https://user-images.githubusercontent.com/1288090/189515365-758bf114-de48-4584-88ff-9733334f9d42.png)
<img width="536" alt="image" src="https://user-images.githubusercontent.com/1288090/189515331-e285e445-ec52-48fa-86c7-5ce27d42d879.png">
<img width="698" alt="image" src="https://user-images.githubusercontent.com/1288090/189515321-a0a25ac1-c06a-48c3-b83e-674a56c20990.png">

**Version**
 - OS: 12.5.1
 - Xcodes: 1.7.0 (15)

**Comment by BarMalka** [comment]
Having the same issue. Doesn't matter which Xcode I'm trying to download.

**Comment by MattKiazyk** [comment]
Related: https://github.com/RobotsAndPencils/XcodesApp/issues/190

@oronbz @BarMalka Sorry for the troubles. In the linked ticket about, we believed it may have something to do with your language setting? We thought we had fixed that issue but perhaps not. 

For completeness do any of your Mac's have a non english language or keyboard? 

Secondly another thing to try is go to the downloads page: https://developer.apple.com/download/all/ and make sure that there is nothing wrong with your account.

Let me know

**Comment by MattKiazyk** [comment]
This should be fixed now with v1.8 that doesn't require any Apple accounts to download Xcode
