### ISSUE TITLE
Skip validation

### ISSUE THREAD

**Issue by medcalc** [RobotsAndPencils/XcodesApp#301]
Could you include the option to skip validation when installing ? (providing this is not already what you do)

xip -x Xcode-14.0.1.xip`.

The `-x` switch skips the validation step

**Comment by Mcrich23** [comment]
why would you want this?

**Comment by medcalc** [comment]
I guess it was to speed things up, but honestly it's been so long I don't remember now... Anyways works fine as is for me.
