### ISSUE TITLE
Command line option to install by build number

### ISSUE THREAD

**Issue by ekurutepe** [RobotsAndPencils/XcodesApp#314]
**Tell us how we can improve Xcodes**
The current command line option to install with release name is error prone. Allowing install by build number would reduce the opportunity for fat fingers. 

In other words: `xcodes install 14B47b` should work in addition to `xcodes install 14.1 Release Candidate 2`

Thanks and keep up the good work!

**Comment by MattKiazyk** [comment]
Hey @ekurutepe - this should belong in [xcodes repo](https://github.com/RobotsAndPencils/xcodes) - but it looks like somebody has an [open PR](https://github.com/RobotsAndPencils/xcodes/pull/232) for it already
