### ISSUE TITLE
Cannot install Xcode 14.1 Release Candidate 2 (14B47b)

### ISSUE THREAD

**Issue by appfrosch** [RobotsAndPencils/XcodesApp#316]
**Describe the bug**
I get the error "Unable to install Xcode" in Xcodes when I try to download Xcode 14.1 Release Candidate 2 (14B47b).
This applies only to this version; the others seem to work just fine.

Please note: I already tried to download from Apple's website which is working fine–so it is _not_ an issue with any updated agreements I did not acknowledge yet.

**To Reproduce**
1. 
  - start Xcodes 
  - check for new Xcode versions
  - tries to automatically download the latest version
2.
  - click on install button for Xcode 14.1 Release Candidate 2 (14B47b)

**Expected behavior**
- recognises new Xcode version 14.1 Release Candidate 2 (14B47b) and downloads it

**Behavior**
The following error message is shown (see also screenshot):
> Unable to install Xcode
The operation couldn't be completed.
(ProcessExecutionError(process:
‹NSConcreteTask: 0x600000e8a0d0>,
standardOutput: "', standardError: ""))

**Screenshots**
<img width="968" alt="CleanShot-CleanShot-20221026-082243" src="https://user-images.githubusercontent.com/91844195/197950323-13b57afa-54ca-4f33-acea-b5ea12dee2ac.png">

**Version**
 - OS: macOS Monterey Version 12.6
 - Xcodes: Version 1.8.0 (16)
 - Xcode failing to install: 14.1 Release Candidate 2 (14B47b) (requires at least macOS 12.5 according to Apple's release notes)

**Comment by MattKiazyk** [comment]
@appfrosch sorry about the problems. There def is something up with your machine. Couple of things to check:
- assuming using Xcode releases data source
- if using aria2 is that installed? 

Does this happen on all versions?

**Comment by lukemmtt** [comment]
I'm experiencing the same error.

**Comment by MattKiazyk** [comment]
If you go to `~/users/XXXXX/Library/Application Support/com.robotsandpencils.xcodesapp` is there any existing downloads stuck there? 

You can get there easily through the `Local Cache Path` in in Settings > Advanced

**Comment by MattKiazyk** [comment]
Tracking with what really happens via: https://github.com/RobotsAndPencils/XcodesApp/issues/320

**Comment by iRayanKhan** [comment]
I am now getting this error when trying to install Xcode 14.3 (14E222b), except with a different code: 0x6000020b1ae0.
I have verified that I am signed into the app, and that I have removed any stuck downloads.
