### ISSUE TITLE
Error when attempting to install Xcode 14.1 (14B47b)

### ISSUE THREAD

**Issue by iosdevben** [RobotsAndPencils/XcodesApp#319]
**Describe the bug**

The below error occurs when I try to install Xcode 14.1 on macOS Monterey 12.6 running on a MacBook Pro Apple M1 Pro (16-inch, 2021) Apple M1 Pro.

I previously had no trouble installing 14.1 beta 3.

I tried uninstalling 14.1 beta 3 to see if that would help, but I still get the error when attempting to install 14.1.

**To Reproduce**
Try to install 14.1

**Expected behavior**

14.1 should installed

**Screenshots**

![image](https://user-images.githubusercontent.com/824608/199344694-b582c40a-494b-4940-ad90-4891c443b2d4.png)

**Version**
 - OS: 12.6
 - Xcodes: 1.8.0

**Comment by MattKiazyk** [comment]
Sorry for the troubles @iosdevben - did the steps in a previous issue: https://github.com/RobotsAndPencils/XcodesApp/issues/316#issuecomment-1292231562 fix your issues?

**Comment by iosdevben** [comment]
> Sorry for the troubles @iosdevben - did the steps in a previous issue: [#316 (comment)](https://github.com/RobotsAndPencils/XcodesApp/issues/316#issuecomment-1292231562) fix your issues?

Yes, that fixed it. Thanks!

**Comment by iosdevben** [comment]
Ig guess the bug is that Xcodes can not recover from this situation without manual intervention from the user.
