### ISSUE TITLE
Xcodes downloads html page as xip file rather than xip

### ISSUE THREAD

**Issue by beeradmoore** [RobotsAndPencils/XcodesApp#320]
(EDIT: I have a workaround in the first comment below but leaving open so devs are notified and can handle http status codes/invalid xip files correctly)

**Describe the bug**
Attempting to download the Xcode 14.1 (current latest) gives an error.

> The operation couldn’t be completed. (ProcessExecutionError(process: <NSConcreteTask: 0x600000886210>, standardOutput: "", standardError: ""))

I did originally get the "downloading 1/6" notification followed by an error (I am not 100% sure if it was the same error). Now hitting install I get the "unarchiving 2/6" notification with the above error. The original error happened a few seconds after I hit install so it is not downloading, unsure why it is skipping to unarchiving.

I have used Xcodes many times in the past without failure. This is the first time since updating to macOS Ventura.

I went and looked at my local Xcode storage that Xcodes downloads to and there is a `Xcode-14.1.0+14B47b.xip` file there. It is 30kb. Opening it up in VSCode I can see it is html. I won't paste the full file but this hopefully gives an indication of why.

```
	<title>Unauthorized - Apple Developer</title>
	<meta name="omni_page" content="Unauthorized" />
	<meta name="Description" content="The page you requested does not exist.">
```

I am not using Xcodes with a logged in Apple account, I have been in the past but I managed to get Xcode 14.0 without being logged in thanks to that great 1.8 update so I don't think it's an issue with my creds being expired or anything.

**To Reproduce**
1. Open Xcodes
2. Click install on Xcode 14.1
 
**Expected behavior**
Xcode installs like it has for me many times in the past.

**Screenshots**
NA

**Version**
 - OS: Ventura (13.0) 
 - Xcodes: 1.8.0 (16)
 - Hardware: 2018 Mac Mini (Intel)

**Comment by beeradmoore** [comment]
Hmm.. Deleting `Xcode-14.1.0+14B47b.xip` allowed it to download correctly, did not need to restart Xcodes.

Going to leave the issue open so devs can see and handle the situation where xip is actually saved as a html file. `available-xcodes.json` doesn't seem to have hash or expected filesize which would be handy to compare against.  Unsure how network implementation is and if you can handle the http status code correctly. My rough as guts approach would be if in step 2 if `Xcode*.xip` is < 10MB maybe consider alerting the user that the file was corrupt and deleting that file from disk. At least in this situation the re-download should have worked correctly.

**Comment by ilawsonlu** [comment]
yes, I have the same problem, just delete the downloaded Xcode, and then install again, it's done

**Comment by MattKiazyk** [comment]
Thanks @beeradmoore - can you (if you still have it) zip up the .xip file so I can see what I can improve there. I'm thinking any file might do, but just in case I would like to get a real example. 

Thanks

**Comment by mladenny** [comment]
I’m not @beeradmoore, but I had the same issue, so here you go: the zipped “.xip” file.

[Xcode-14.1.0+14B47b.xip.zip](https://github.com/RobotsAndPencils/XcodesApp/files/9922035/Xcode-14.1.0%2B14B47b.xip.zip)

**Comment by beeradmoore** [comment]
My file was gone. I checked the one from @mladenny and it looked very very similar (if not the same) to mine.

**Comment by MartinP7r** [comment]
The same is happening for me.

[Xcode-14.0.1+14A400.xip.zip](https://github.com/RobotsAndPencils/XcodesApp/files/10012332/Xcode-14.0.1%2B14A400.xip.zip)

**Comment by MattKiazyk** [comment]
Closing - track through #323
