### ISSUE TITLE
Open in Rosetta

### ISSUE THREAD

**Issue by cyrillelegrand** [RobotsAndPencils/XcodesApp#321]
It would be nice to have a quick toggle for changing the flag "Opens in Rosetta" faster than using the Finder.

I have some old projects at work that need to work in Intel mode and it's a pain to have to toggle it manually every time.

**Comment by KORraNpl** [comment]
Just a note - starting from Xcode 14.3 Beta 1, it's not possible to launch Xcode with Rosetta:

> [Deprecations in Xcode 14.3 Beta](https://developer.apple.com/documentation/xcode-release-notes/xcode-14_3-release-notes#Deprecations-in-Xcode-143-Beta)
> 
>     Xcode isn’t supported under Rosetta. See Developer Technote [“Resolving architecture build errors on Apple silicon“](https://developer.apple.com/documentation/technotes/tn3117-resolving-build-errors-for-apple-silicon) for more information. (92772361)

**Comment by MattKiazyk** [comment]
Yeah I saw that, but the code was merged in before beta came out - it'll probably be removed at some point in the future now!
