### ISSUE TITLE
Cannot download and install some version of Xcode

### ISSUE THREAD

**Issue by hackenbacker** [RobotsAndPencils/XcodesApp#323]
**Describe the bug**
When I try to install Xcode, I get the following error message.

Could not install Xcode
This archive "Xcode-11.7.0+11E801a.zip" is corrupt and cannot be expanded.

I downloaded it directly from xcodereleases.com with success.

**To Reproduce**
Data Source = "Xcode Releases"
1) Select 11.7 (11E801a). or 12.5.1 (12E507).
2) Push [Install] button.
3) Then the error message appears.

**Expected behavior**
Starts downloading selected Xcode normally.

**Screenshots**
<img width="370" alt="SS_2022-11-15_14 06 13" src="https://user-images.githubusercontent.com/22875818/201831630-1c60a050-5ab7-41a3-a2ac-633e5772f90c.png">

**Version**
 - OS: macOS Ventura 13.0.1
 - Xcodes: 1.8.0 with Japanese Language.

**Comment by iseruuuuu** [comment]
I face same problem

**Comment by andreasheick-isobar** [comment]
Same issue here

**Comment by karim-elgendy** [comment]
Yup, suffering the same problem

**Comment by MattKiazyk** [comment]
Hey everyone. It looks like Apple has blocked the way we were getting a download token without having to log in, which is causing this issue. 😢 

Workaround for now is to switch to Apple datasource and download using the original way with your Apple username/password.

**Comment by leon-wolf** [comment]
What about reimplementing the old download with login as a fallback if download without login fails?

**Comment by b-onc** [comment]
@MattKiazyk When I switch to Apple datasource, I immediately get the error "Unable to update selected Xcode" and when I tap refresh, the same error appears. Install attempt on any Xcode version shows the same error.

**Comment by MattKiazyk** [comment]
> What about reimplementing the old download with login as a fallback if download without login fails?

@leon-wolf Yes a new version will at least flip back to the requirement of login. 




> @MattKiazyk When I switch to Apple datasource, I immediately get the error "Unable to update selected Xcode" and when I tap refresh, the same error appears. Install attempt on any Xcode version shows the same error.

@b-onc One thing you can try is to delete the bad `xip` file. Delete any file at `~/Library/Application Support/com.robotsandpencils.xcodes`

**Comment by MattKiazyk** [comment]
New 1.9.0 version was released tonight that should fix the downloading and revert back to having to use username/password.

**Comment by b-onc** [comment]
I cleared my local cache but still the same issue
