### ISSUE TITLE
Can't install any version of xcode

### ISSUE THREAD

**Issue by pqhcker** [RobotsAndPencils/XcodesApp#326]
**Describe the bug**
When I try to install any version of xcode, always prompt this error screen, I saw some bug reported, and I already delete files in Application Support Folder, but the problem persists.

**To Reproduce**
Click on install button

**Expected behavior**
Install Xcode selected version

**Screenshots**
<img width="915" alt="Xcodes_y_alejandrosolano_—_-zsh_—_80×24_y_GitHub_-_RobotsAndPencils_XcodesApp__The_easiest_way_to_install_and_switch_between_multiple_versions_of_Xcode_-_with_a_mouse_click_" src="https://user-images.githubusercontent.com/5551726/201973545-1a58a4d8-0729-4a13-9118-cd46a037740f.png">

**Version**
 - OS: Mac OSX Ventura 13.0.1

 - Xcodes: 1.8.0

**Comment by pqhcker** [comment]
Ok, it seems that if I change the data source, instead of using XCode Releases I use Apple, it starts working for some reason, I still don't know if it installs but I'll let you know

**Comment by MattKiazyk** [comment]
Closing track through #323
