### ISSUE TITLE
Error downloading any version: "Date string does not match format expected by formatter"

### ISSUE THREAD

**Issue by yossizahn** [RobotsAndPencils/XcodesApp#329]
**Describe the bug**
I get an error downloading any version: "Date string does not match format expected by formatter"
The full message is:
```
The operation couldn’t be completed. (Error.dataCorrupted(Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "downloads", intValue: nil), _JSONKey(stringValue: "Index 2", intValue: 2), CodingKeys(stringValue: "dateModified", intValue: nil)], debugDescription: "Date string does not match format expected by formatter.", underlyingError: nil)))
```
The actual value in the JSON (at `["downloads"][2]["dateModified"]` retrieved through `mitmproxy`) is:
```
03/23/12 02:18
```

**To Reproduce**
Try downloading any version of Xcode using Xcodes

**Expected behavior**
It should work...

**Version**
 - OS: 13.0.1
 - Xcodes: 1.9.0

**Comment by yossizahn** [comment]
Maybe applicable:
![CleanShot 2022-11-23 at 12 32 03@2x](https://user-images.githubusercontent.com/19174667/203525047-5d1b55f8-bd09-427d-80df-32f87273e32c.png)

**Comment by yossizahn** [comment]
I got it
The hour from 2AM to 3AM on the specific date does not exist due to skipping an hour for DST :facepalm:

Now what?

**Comment by yossizahn** [comment]
Test code:
```swift 
import Foundation

let df = DateFormatter()
df.dateFormat = "MM/dd/yy HH:mm"
print(df.date(from: "03/23/12 02:18"))
```

**Comment by yossizahn** [comment]
Found this:
https://stackoverflow.com/questions/71415071/swift-date-parsing-on-daylight-saving-time

**Comment by BenjiMandel** [comment]
Did you get the app working? I have this issues every so often, and its really annoying

**Comment by yossizahn** [comment]
This problem only exists in certain timezones. Changing your timezone in System Settings (temporarily, while downloading a new xcode) will solve the issue
