### ISSUE TITLE
I can't authorize with apple id

### ISSUE THREAD

**Issue by gre4ixin** [RobotsAndPencils/XcodesApp#332]
**Describe the bug**
I try to login with my Apple ID and I received an error with code 412.

**To Reproduce**

**Expected behavior**

**Screenshots**
"Received error code 412"

**Version**
 - OS: 12.6.1 (21G217)
 - Xcodes: 1.9.0

**Comment by johnconion** [comment]
same issue: https://github.com/RobotsAndPencils/XcodesApp/issues/189
