### ISSUE TITLE
download xcode14.2 error

### ISSUE THREAD

**Issue by Charlotte3240** [RobotsAndPencils/XcodesApp#335]
**Describe the bug**
此压缩文件“Xcode-14.2.0+14C18.xip”已损坏且无法解压。

**To Reproduce**
download xcode 14.2

**Screenshots**
<img width="900" alt="图片" src="https://user-images.githubusercontent.com/13010614/207480674-8a83b794-bed6-410d-a53a-50c805a70432.png">

**Version**
 - OS: 12.6
 - Xcodes: 1.8.0（16）

**Comment by TheLittleBoy** [comment]
升级到V1.9.0就可以了。

**Comment by JackYoustra** [comment]
If you upgraded after initiating the download (like I did), you may have to delete the malformed downloaded fragment in the local cache path (in settings) in order to get it to work.

**Comment by BrentMifsud** [comment]
tried deleting the local cache. Does not fix the issue.

**Comment by MattKiazyk** [comment]
@BrentMifsud @Charlotte3240  I see you're on 1.8. Please update to 1.9 which should fix your issue.

**Comment by BrentMifsud** [comment]
Will do.

**Comment by lvalenta** [comment]
1.9 and deleting cache fixed the issue for me.

**Comment by eglantinefonrose** [comment]
I have done the following, but I keep facing the "Unable to install Xcode" problem:
 - I have version 1.9
 - I have cleared the cache (I've even used a new directory)
 - I'm logged in on my Apple account inside XCodes.app. 
 
 I'm on macOS 13.1 (22C65), MacBook Pro M1 14.
<img width="796" alt="XCodesApp install issue" src="https://user-images.githubusercontent.com/41706650/209412346-92092fb7-48de-4bce-bb24-b9c4b1d2a518.png">

I'm *not* facing the same issue on another Mac which is running macOS 12.3.1 (MBP M1 16"). The install doesn't block on this other machine (it's macOS 12.3.1 so I can't start Xcode 14.2 but the version is downloaded without any issue)

**Comment by k-ruben** [comment]
I'm facing the same issue. I updated to the latest version and deleted the cache, and later even changed the directory. Same problem with 1.8.0 and 1.9.0.
I then tried the cli which also doesn't work but gives a better error message. It takes roughly two seconds until the error happens.

![Bildschirmfoto 2023-01-10 um 14 54 35](https://user-images.githubusercontent.com/48501039/211569760-a56868e0-5012-4a55-8223-c4899f8f90cd.png)

**Comment by k-ruben** [comment]
For some reason, it works again. Yesterday I downloaded one version manually directly from apple which got recognized by xcodes. For my tooling I had the problem, that I had no `xcode` Application, only `xcode-<version.number>`. After I fixed that, I did `sudo xcode-select --reset` which (I think) fixed "You have to install development tools first"
Today I tried to use xcodes again, and now it works. I'm not sure what exactly fixed it, but maybe it helps other people

**Comment by usagimaru** [comment]
I'm not sure how solve this problem.
Using v1.9.0 (17)
