### ISSUE TITLE
Unable to install Xcode: "ProcessExecutionError"

### ISSUE THREAD

**Issue by iandundas** [RobotsAndPencils/XcodesApp#338]
**Describe the bug**
I couldn't download Xcode 14.2 until I deleted `~/Library/Application Support/com.robotsandpencils.XcodesApp` & restarted Xcodes. I was able to kick off downloading other versions of Xcode, though I didn't run those to completion as part of the test.

**To Reproduce**
Here is my corrupt `com.robotsandpencils.XcodesApp` folder, I guess replace yours with this to experience the issue:

[com.robotsandpencils.XcodesApp.zip](https://github.com/RobotsAndPencils/XcodesApp/files/10267052/com.robotsandpencils.XcodesApp.zip)

**Expected behavior**
Download of Xcode 14.2 should complete.

**Screenshots**
![CleanShot 2022-12-20 at 10 14 29@2x](https://user-images.githubusercontent.com/1131967/208629917-ea6a7258-4535-43b3-bb6b-d9452ef47f32.png)

**Version**
 - OS: Ventura 13.1
 - Xcodes: 1.9.0 (17)

**Comment by manucodin** [comment]
Same error here 🙁

**Comment by totoroyyb** [comment]
Same error on macOS Ventura 13.0.1 (22A400)

**Comment by totoroyyb** [comment]
https://github.com/RobotsAndPencils/XcodesApp/issues/325#issuecomment-1364730315

This solves the problem

**Comment by totoroyyb** [comment]
Remember to log in with Apple ID first due to the reported issue here #323

**Comment by manucodin** [comment]
> [#325 (comment)](https://github.com/RobotsAndPencils/XcodesApp/issues/325#issuecomment-1364730315)
> 
> This solves the problem

This solves my problem

**Comment by MattKiazyk** [comment]
Closing this as steps to fix have been outline - thanks!

**Comment by iandundas** [comment]
Fair enough but .. 🤔 it would I think be better if the app handled working around this invalid state, rather than requiring user intervention to go and manually clear a cache. Or at least gave a better error dialog than the one in the screenshot.
