### ISSUE TITLE
Unable to install xcode

### ISSUE THREAD

**Issue by Jayian1890** [RobotsAndPencils/XcodesApp#353]
**Describe the bug**
Does not install. Returns error. "Unable to install xcode"

**To Reproduce**
Click install on any available Xcode option

**Expected behavior**
install xcode

**Screenshots**
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/637445/217830509-b810d41d-b968-48b8-990c-4d3a3c8a7540.png">

**Version**
 - OS: Ventura 13.2
 - Xcodes: None

**Comment by dermaaarkus** [comment]
Somehow I am not able to install the latest stable Xcode version, too. 

<img width="1012" alt="Bildschirm­foto 2023-02-19 um 10 52 08" src="https://user-images.githubusercontent.com/7196958/219940898-88f46a24-f606-4c12-bede-6367e949cb49.png">

**Comment by soooku** [comment]
I have same issue
- Chip Apple M2 Pro
- OS: Ventura 13.2
- Xcodes: 1.9.0 (17)

**Comment by BobBlueBeck** [comment]
Same issue here.  Apple M2 Pro, Ventura 13.0.
Trying to install any version results in the same error as that of the OP.

**Comment by MattKiazyk** [comment]
Hi. 

Please update to 1.10.0 - it has some critical fixes for logging in. Apple added some different security that if not used, caused Apple Accounts to be locked out - see PR https://github.com/RobotsAndPencils/XcodesApp/pull/361

**Comment by BobBlueBeck** [comment]
Hi Matt,

I discovered that it was in fact because I hadn't agreed to the Apple dev
agreement, and although I tried to go back and remove my comment, I
couldn't even find it again.  Not sure what was happening there, but please
delete.

Cheers,

Bob

**Comment by MattKiazyk** [comment]
hi @BobBlueBeck thanks - There's some work to do there for that scenario to better handle it.
