### ISSUE TITLE
'xcodes runtimes install' fails on Apple Silicon Mac

### ISSUE THREAD

**Issue by mc7h** [RobotsAndPencils/XcodesApp#355]
**Describe the bug**

`sudo xcodes runtimes install "iOS 15.5"` fails. 

**To Reproduce**
Run:
`sudo xcodes runtimes install "iOS 15.5" --keep-archive`        
or
`sudo xcodes runtimes install "iOS 15.5"`

Observed on my M1 machine; verified by my colleague on theirs.

Works just fine on an Intel machine I had access to.

**Expected behavior**
The simulator runtime should install successfully.
```
Downloading Runtime iOS 15.5: 100%
Mounting DMG
Installing Runtime
Deleting Archive
Finished
```

**Screenshots**
```
Installing Runtime
Error: Failed executing: `/usr/sbin/installer -pkg 
/Users/mc7h/Library/Caches/com.robotsandpencils.xcodes/com.apple.pkg.iPhoneSimulatorSDK15_5.pkg -target /` (1).
```

**Version**
 - OS: 13.1  (Apple M1 Pro)
 - Xcodes: 1.2.0

**Comment by MattKiazyk** [comment]
Hi @mc7h - can you post this issue to the [xcodes repo](https://github.com/RobotsAndPencils/xcodes/issues)?
