### ISSUE TITLE
Apple ID is locked after signing in: Unable to Sign In

### ISSUE THREAD

**Issue by wvabrinskas** [RobotsAndPencils/XcodesApp#360]
**Describe the bug**
I am unable to sign into my apple id. My apple ID has 2FA and when i go to sign into Xcodes with my password, I get the proper popups for the 2FA code but then Xcodes seems to fail to login. This worked before. 

**To Reproduce**
1. Login with an account with 2FA. 
2. Observe error

**Expected behavior**
Successful log in
**Screenshots**

![image](https://user-images.githubusercontent.com/934347/220814592-a4f4c6fa-f379-499b-9d84-59b8822abc53.png)

**Version**
 - OS: 13.2.1
 - Xcodes: 1.9.0

**Comment by MattKiazyk** [comment]
Hi @wvabrinskas 

That url in the error gives - https://support.apple.com/en-ca/HT212522 which says `If you see this message after attempting to sign in with a new device or web browser, wait for at least 24 hours, then try to sign in again.` 

I'm guessing your Apple ID is locked for a bit? If it doesn't work on Xcodes, another way to test is to log into developer.apple.com and make sure it works there. 

Thanks

**Comment by wvabrinskas** [comment]
Ah I did reset my password. What was weird was Xcodes is what triggered the lock actually... so weird

**Comment by dhinakg** [comment]
I got my account locked by something else, but I'm also experiencing this issue. I changed my password and while I can log in on the developer page, I can't log in to Xcodes nor the thing that got me locked in the first place. Both show me this error but I still get the 2FA code prompt on my devices anyway.

**Comment by carmichaelalonso** [comment]
I am experiencing the same issue, but it seems that signing in through Xcodes caused the account to be locked. I tried with two separate Apple IDs (personal and work) and both were locked after trying to sign in this way.

Worth noting that I was trying to sign in through a build server in a cloud data centre, which could also be a reason why the account was locked. Just sharing my experience here in case it helps narrow things down.

**Comment by wvabrinskas** [comment]
Yeah it seems however Xcodes is authenticating is causing accounts to be locked. At least that's what happened with me, and it seems a few others

**Comment by MattKiazyk** [comment]
Thanks everybody.. it happens to me too. I'll see what i can find. Hopefully it's just a temporary thing. 

![image](https://user-images.githubusercontent.com/1119565/220938518-0dd9e37b-8cd8-4643-8f92-acccb72a6ebf.png)

**Comment by MattKiazyk** [comment]
Update: After getting locked out of the Apple ID, via my Mac, I was forced to reset my Apple ID password (via my phone). Xcodes seems to be working as it should and I can now download normally. 

Is this what everyone else is seeing?

**Comment by wvabrinskas** [comment]
> Update: After getting locked out of the Apple ID, via my Mac, I was forced to reset my Apple ID password (via my phone). Xcodes seems to be working as it should and I can now download normally. 
> 
> 
> 
> Is this what everyone else is seeing? 

Will try again. I'm almost afraid to get locked out again. I have so many devices 😆

**Comment by MattKiazyk** [comment]
> Will try again. I'm almost afraid to get locked out again. I have so many devices 😆

Yeah I hear you! 

The password I had for my Apple ID I had been using for a really long time. (I probably shouldn't say that). Wondering if that had anything to do with it? Perhaps Apple cracking down?

**Comment by MattKiazyk** [comment]
It's not just Xcodes - Fastlane is having similar issues! https://github.com/fastlane/fastlane/issues/21071

**Comment by MattKiazyk** [comment]
Via the fastlane issue above, users are also getting locked out of their accounts using Xcode archiver! 

Happy Thursday!

**Comment by carmichaelalonso** [comment]
Nice find, happy Thursday indeed :)

**Comment by ptrkstr** [comment]
I used 3 different apple accounts and all were locked out the moment I attempted to sign into Xcodes.

**Comment by wvabrinskas** [comment]
Okay so then I won't be trying lol

**Comment by wvabrinskas** [comment]
> It's not just Xcodes - Fastlane is having similar issues! [fastlane/fastlane#21071](https://github.com/fastlane/fastlane/issues/21071)

Woah wild. I wonder what's going on...

**Comment by dhinakg** [comment]
Spent my afternoon digging through this, here's notes on the new hashcash addition: https://github.com/fastlane/fastlane/issues/21071#issuecomment-1442442083

**Comment by MattKiazyk** [comment]
@dhinakg I saw that - thanks for all your work! I'm looking at implementing it.

Do you happen to have some of those values so that I can write a proper test? I was trying to follow it through on the website, but I'm not seeing any header with the final `x-apple-hc` header value

**Comment by dhinakg** [comment]
```
X-Apple-HC-Bits: 10
X-Apple-HC-Challenge: bb63edf88d2f9c39f23eb4d6f0281158
```

With this case, if you set the timestamp to `20230224001754`, you'd construct `1:10:20230224001754:bb63edf88d2f9c39f23eb4d6f0281158::COUNTER`, and if you start from 0 you should end up at the counter being `866`, so you'd set `X-APPLE-HC` to `1:10:20230224001754:bb63edf88d2f9c39f23eb4d6f0281158::866`

`X-APPLE-HC` is set on the request to `https://idmsa.apple.com/appleauth/auth/signin?isRememberMeEnabled=true` in a browser:

<img width="914" alt="image" src="https://user-images.githubusercontent.com/17605561/221060760-3b97fca0-4064-4b98-b7e5-e7a22acceb33.png">

**Comment by MattKiazyk** [comment]
@dhinakg I'll prefix with I think I'm doing something wrong but I tried to implement the hashcash algorithm with your inputs and I'm not getting the same counter as what you have.

https://github.com/RobotsAndPencils/XcodesApp/pull/361

So I'm getting `1:10:20230224001754:bb63edf88d2f9c39f23eb4d6f0281158::1092` instead of 866. If you have some time to perhaps see what is wrong with my code?

**Comment by joshdholtz** [comment]
@MattKiazyk There is logic for this in this _fastlane_ PR 👉  https://github.com/fastlane/fastlane/pull/21073

Appfigures was nice enough to share the spec with us 😊

**Comment by alexcroox** [comment]
I was locked out of my Apple account yesterday when using "login with apple" on a random site, never happened before. I'm guessing something went live to cause that across all platforms and integrations.

**Comment by MattKiazyk** [comment]
Thanks @joshdholtz and Appfigures!

Work has me busy today but I hope to get the PR up this weekend!

**Comment by wvabrinskas** [comment]
> I was locked out of my Apple account yesterday when using "login with apple" on a random website, never happened before. I'm guessing something went live to cause that across all platforms and integrations.

that's wild

**Comment by bryanjclark** [comment]
Same thing happened to me - but I have a sense that the issue isn’t over.

I wound up needing to reset my phone to factory settings this morning, because my PIN code stopped working.

On attempting to restore my phone from backup, though? **iCloud Backups are not loading,** and aren’t visible on my other devices. Also, can’t login to “iMessage in the Cloud”.

_Could somebody else here check if they’re able to view their iCloud Backups in Settings.app?_ I’m concerned that there’s a larger issue with my AppleID as a result of all of this…

**Comment by MattKiazyk** [comment]
Hey Everybody

Implemented the fix in  https://github.com/RobotsAndPencils/XcodesApp/pull/361 

If somebody would be so kind as to download that PR and see if that works? 

Note: If your account is locked already this doesn't FIX your account. You must unlock your account and from that point forward the Xcodes login won't lock your account. 🤞

**Comment by wvabrinskas** [comment]
@MattKiazyk trying now

**Comment by wvabrinskas** [comment]
@MattKiazyk  worked a treat!! Thank you so much

**Comment by shimastripe** [comment]
Thanks for the great improvements! Does this need to be addressed for the CLI tool as well? https://github.com/RobotsAndPencils/Xcodes
