### ISSUE TITLE
Prerelease versions are shown when "Include prerelease versions" is unchecked

### ISSUE THREAD

**Issue by civatrix** [RobotsAndPencils/XcodesApp#67]
On first launch of the app I noticed all the beta and release candidate versions were listed. I looked for a way to hide those and only show full release versions. The closest option I could find was `Updates -> Include prerelease versions` which was already unchecked. Maybe this is because I was using the command line tool previously?

**Comment by interstateone** [comment]
The Updates preference pane, including that checkbox, is for software updates of Xcodes itself, but I can see now how this might not be clear. Perhaps we can change the copy in that pane to resolve this.

There is currently no way to filter the list of Xcode versions to only show release versions, which matches the behaviour of `xcodes`.

**Comment by civatrix** [comment]
That makes sense. Maybe include the word `app` in the descriptions?

`Automatically check for app updates`
`Include prerelease app versions`
