### ISSUE TITLE
"Make Active" button doesn't work until after restarting app

### ISSUE THREAD

**Issue by civatrix** [RobotsAndPencils/XcodesApp#68]
I installed the privileged helper from the options menu but the `Make active` button continued to do nothing until after I quit the app and reopened.

**Comment by interstateone** [comment]
I can't reproduce this with the latest commit on `main` (9a2057bcd5a3d4e6ebcc1c272b2b5a855c398b59), but I'm going to leave it open for a few days after the next release in case it's a "works on my computer" situation.

**Comment by weitieda** [comment]
I'm on 1.0.5(6), make active doesn't work even quit and reopen. macOS 11.2.1


https://user-images.githubusercontent.com/35972055/113238660-330a2b00-9277-11eb-9fff-3dc13e60180e.mp4
