### ISSUE TITLE
Install helper error shown multiple times after cancel install

### ISSUE THREAD

**Issue by MattKiazyk** [RobotsAndPencils/XcodesApp#69]
Issue: 
If I hit cancel on the privileged helper I shouldn't be prompted multiple times saying it couldn't communicate with helper app. It should just cancel

RepoSteps:

1. Tapped `Make Active` 
2. Hit cancel on the prompt

![image](https://user-images.githubusercontent.com/1119565/105238889-5061a100-5b32-11eb-8780-16d665332f3b.png)
3. Prompted multiple times with error 
![image](https://user-images.githubusercontent.com/1119565/105239995-94ed3c80-5b32-11eb-97a3-9a62522a9691.png)

This may be resolved with changes in #66

**Comment by interstateone** [comment]
👍 This might be done as part of #66 but we can track it separately. We need to actually return whether installation succeeded from HelperClient.install so whatever was waiting on it can proceed or abort. Right now the things that require the helper will proceed after it's done blocking the queue regardless of whether it worked or not.
