### ISSUE TITLE
Install instructions should instruct user to move app to /Applications

### ISSUE THREAD

**Issue by MattKiazyk** [RobotsAndPencils/XcodesApp#70]
Got this message after checking `Include prerelease versions` 

![image](https://user-images.githubusercontent.com/1119565/105241573-7b002980-5b33-11eb-87c8-7919d20fc0e0.png)

**Comment by interstateone** [comment]
Ah, good catch, I forgot about this in #13. I don't know if this is the best implementation but we probably want something like this included in the app https://github.com/potionfactory/LetsMove/.
