### ISSUE TITLE
Support installation in an alternative directory

### ISSUE THREAD

**Issue by interstateone** [RobotsAndPencils/XcodesApp#8]
- Xcodes should support managing Xcode versions in a single directory, which defaults to /Applications
- Advanced preference pane should contain a field that displays the current directory. This should be stored in UserDefaults / AppStorage.
- Xcodes should install new versions into this directory
- Xcodes should detect installed versions in this directory

This should match the functionality of `xcodes`' `--directory` flag.

In the past I haven't had a reliable experience using Spotlight to find Xcodes on disk, and I think most people would have them installed in a single directory, so Spotlight wouldn't really add any value in that situation.

**Comment by VaslD** [comment]
Just my 2¢. If this gets implemented, it's better to WARN user when they change installation directory, that they may occasionally run into bugs (from Xcode and related developer tools like CocoaPods) if Xcode was not installed in `/Applications`; and that doing so should not be recommended.
