### ISSUE TITLE
Display File Size in Info panel

### ISSUE THREAD

**Issue by kurisubrooks** [RobotsAndPencils/XcodesApp#94]
**Tell us how we can improve Xcodes**
Ideally, I'd like to be able to see the size of the Xcode release before downloading it (as I have a fairly limited data connection, so this information is important to me.)

**Is your feature request related to a problem? Please describe.**
No.

**What would you like to see? How would you like it to work?**
In the info panel, upon clicking a release, display the file size of the release. Just text is fine, no need to be fancy.

**Comment by MattKiazyk** [comment]
Hi @kurisubrooks 

If you install the latest version of xcodes you'll see the download size is now in the info panel when using the Apple data source. When using the xcodereleases, it unfortunately is not, as that requires some changes to a 3rd party (open source) tool which I've created a PR for that will hopefully be accepted. 

Furthermore however, once you start downloading, the file size does show up in either data source. Hopefully that will help you. 

I'm going to close this issue for now. If you have any new issues - please feel free to create a new issue. 

Thanks
