### ISSUE TITLE
Auto download

### ISSUE THREAD

**Issue by jacobwhite** [RobotsAndPencils/XcodesApp#99]
I really hate waiting for Xcode to download and expand. Would be super cool if this app could check for new versions of Xcode and get the process going in the background so I do r feel like I’m having to wait so long.

**Comment by Kamik423** [comment]
And then have options to either always download the latest beta or release version. And for checking every night or every hour and so on. I love it!

**Comment by jacobwhite** [comment]
Yeah, maybe some options for how many old versions to keep around.

**Comment by jacobwhite** [comment]
Oh hell yeah!

**Comment by jacobwhite** [comment]
So I'm just now getting around to trying this out. Latest RC build is downloading now. Do I need to run xcodes.app for it to check for updates? Or does it do this in the background? Can I close the app while its downloading?

**Comment by MattKiazyk** [comment]
Yes.. currently Xcodes.app needs to be running in order for it to work and only checks every 6 hours.

There are enhancements for sure around this. One thing I noticed is if I close my laptop and reopen it won't auto check until I foreground the app.

**Comment by jacobwhite** [comment]
Maybe it should run as a menubar app.
